name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write    # Allows pushing changes to the repository
  packages: write    # Allows publishing Docker images
  workflows: read    # Allows reading workflow files (adjust to write if needed)
  secrets: read      # Allows accessing repository secrets
  commit-statuses: write # Allows updating commit statuses (if needed)
  deployments: write # Allows managing deployments (if needed)
  actions: read      # Allows viewing Actions workflows, runs, and artifacts (adjust to write if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                     --cache-to=type=local,dest=/tmp/.buildx-cache \
                     -t ${{ secrets.DOCKER_USERNAME }}/exp-tracker-render:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/exp-tracker-render:latest
